name: Build Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Website
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: git submodule update --init --recursive
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cp CNAME build/web/CNAME
          cd build/web
          git init
          git config --global user.email nik-bot@nikmoores.com
          git config --global user.name Nik-bot
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/Adroz/manager-toolkit-website.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Update GitHub Pages"
          git push origin gh-pages -f
